services:
  database:
    image: "postgres"
    network_mode: "host"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simplehosting_slick
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/var/lib/postgresql/data
  web:
    image: kirieshki/simple-hosting.web2:2023.12.02.1
    network_mode: "host"
    ports:
      - "9000:9000"
  compositor:
    image: kirieshki/simple-hosting.compositor:latest
    network_mode: "host"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

