FROM ubuntu:latest

#Update environment
RUN apt update -y --fix-missing
RUN apt upgrade -y

#Install NPM
RUN apt install nodejs -y
RUN apt install npm -y

#Install ZIP-Archiver
RUN apt install zip -y
